name: Test and build demo

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install
        run: |
          cargo install -f wasm-bindgen-cli wasm-opt
          rustup target add wasm32-unknown-unknown
          npm install
      - name: Build wasm
        run: make
      - name: Test Node.js
        run: |
          npm test
      - name: Build web
        run: |
          cd ${GITHUB_WORKSPACE}/demo/web
          npm install
          PUBLIC_URL='/simplecc-wasm/' npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/web/dist
